# How Do You Traverse Through A Dictionary Object In Python? 

'''

1) Using dict. items() Method. ...
2) Using Keys() Method. ...
3) Using Values() Method. ...
4) Iterating with Index. ...
5) Iterating Over Dictionary In Alphabetical Order. ...
6) Sort Using Dictionary Item Values

'''
